export default [
    [
        {
            code: 'Backquote',
            en_char: '`',
            ru_char: 'ё',
            ru_shiftChar: 'Ё',
            en_shiftChar: '~',
        },
        {
            code: 'Digit1',
            char: '1',
            shiftChar: '!',
        },
        {
            code: 'Digit2',
            char: '2',
            ru_shiftChar: '"',
            en_shiftChar: '@',
        },
        {
            code: 'Digit3',
            char: '3',
            ru_shiftChar: '№',
            en_shiftChar: '#',
        },
        {
            code: 'Digit4',
            char: '4',
            ru_shiftChar: ';',
            en_shiftChar: '$',
        },
        {
            code: 'Digit5',
            char: '5',
            shiftChar: '%',
        },
        {
            code: 'Digit6',
            char: '6',
            ru_shiftChar: ':',
            en_shiftChar: '^',
        },
        {
            code: 'Digit7',
            char: '7',
            ru_shiftChar: '?',
            en_shiftChar: '&',
        },
        {
            code: 'Digit8',
            char: '8',
            shiftChar: '*',
        },
        {
            code: 'Digit9',
            char: '9',
            shiftChar: '(',
        },
        {
            code: 'Digit0',
            char: '0',
            shiftChar: ')',
        },
        {
            code: 'Minus',
            char: '-',
            shiftChar: '_',
        },
        {
            code: 'Equal',
            char: '=',
            shiftChar: '+',
        },
        {
            code: 'Backslash',
            char: '\\',
            ru_shiftChar: '/',
            en_shiftChar: '|',
        },
        {
            code: 'Backspace',
            display: '←',
        },
    ],
    [
        {
            code: 'Tab',
            display: 'Tab',
        },
        {
            code: 'KeyQ',
            en_char: 'q',
            ru_char: 'й',
            ru_shiftChar: 'Й',
            en_shiftChar: 'Q',
        },
        {
            code: 'KeyW',
            en_char: 'w',
            ru_char: 'ц',
            ru_shiftChar: 'Ц',
            en_shiftChar: 'W',
        },
        {
            code: 'KeyE',
            en_char: 'e',
            ru_char: 'у',
            ru_shiftChar: 'У',
            en_shiftChar: 'E',
        },
        {
            code: 'KeyR',
            en_char: 'r',
            ru_char: 'к',
            ru_shiftChar: 'К',
            en_shiftChar: 'R',
        },
        {
            code: 'KeyT',
            en_char: 't',
            ru_char: 'е',
            ru_shiftChar: 'Е',
            en_shiftChar: 'T',
        },
        {
            code: 'KeyY',
            en_char: 'y',
            ru_char: 'н',
            ru_shiftChar: 'Н',
            en_shiftChar: 'Y',
        },
        {
            code: 'KeyU',
            en_char: 'u',
            ru_char: 'г',
            ru_shiftChar: 'Г',
            en_shiftChar: 'U',
        },
        {
            code: 'KeyI',
            en_char: 'i',
            ru_char: 'ш',
            ru_shiftChar: 'Ш',
            en_shiftChar: 'I',
        },
        {
            code: 'KeyO',
            en_char: 'o',
            ru_char: 'щ',
            ru_shiftChar: 'Щ',
            en_shiftChar: 'O',
        },
        {
            code: 'KeyP',
            en_char: 'p',
            ru_char: 'з',
            ru_shiftChar: 'З',
            en_shiftChar: 'P',
        },
        {
            code: 'BracketLeft',
            en_char: '[',
            ru_char: 'х',
            ru_shiftChar: 'Х',
            en_shiftChar: '{',
        },
        {
            code: 'BracketRight',
            en_char: ']',
            ru_char: 'ъ',
            ru_shiftChar: 'Ъ',
            en_shiftChar: '}',
        },
        {
            code: 'Delete',
            display: 'Delete',
         
        },
       
    ],
    [
        {
            code: 'CapsLock',
            display: 'CapsLk ⇪',
        },
        {
            code: 'KeyA',
            en_char: 'a',
            ru_char: 'ф',
            ru_shiftChar: 'Ф',
            en_shiftChar: 'A',
        },
        {
            code: 'KeyS',
            en_char: 's',
            ru_char: 'ы',
            ru_shiftChar: 'Ы',
            en_shiftChar: 'S',
        },
        {
            code: 'KeyD',
            en_char: 'd',
            ru_char: 'в',
            ru_shiftChar: 'В',
            en_shiftChar: 'D',
        },
        {
            code: 'KeyF',
            en_char: 'f',
            ru_char: 'а',
            ru_shiftChar: 'А',
            en_shiftChar: 'F',
        },
        {
            code: 'KeyG',
            en_char: 'g',
            ru_char: 'п',
            ru_shiftChar: 'П',
            en_shiftChar: 'G',
        },
        {
            code: 'KeyH',
            en_char: 'h',
            ru_char: 'р',
            ru_shiftChar: 'Р',
            en_shiftChar: 'H',
        },
        {
            code: 'KeyJ',
            en_char: 'j',
            ru_char: 'о',
            ru_shiftChar: 'О',
            en_shiftChar: 'J',
        },
        {
            code: 'KeyK',
            en_char: 'k',
            ru_char: 'л',
            ru_shiftChar: 'Л',
            en_shiftChar: 'K',
        },
        {
            code: 'KeyL',
            en_char: 'l',
            ru_char: 'д',
            ru_shiftChar: 'Д',
            en_shiftChar: 'L',
        },
        {
            code: 'Semicolon',
            en_char: ';',
            ru_char: 'ж',
            ru_shiftChar: 'Ж',
            en_shiftChar: ':',
        },
        {
            code: 'Quote',
            en_char: "'",
            ru_char: 'э',
            ru_shiftChar: 'Э',
            en_shiftChar: '"',
        },
        {
            code: 'Enter',
            display: 'Enter ↵',
        },
    ],
    [
        {
            code: 'ShiftLeft',
            display: 'Shift ⇧',
        },
        {
            code: 'KeyZ',
            en_char: 'z',
            ru_char: 'я',
            ru_shiftChar: 'Я',
            en_shiftChar: 'Z',
        },
        {
            code: 'KeyX',
            en_char: 'x',
            ru_char: 'ч',
            ru_shiftChar: 'Ч',
            en_shiftChar: 'X',
        },
        {
            code: 'KeyC',
            en_char: 'c',
            ru_char: 'с',
            ru_shiftChar: 'С',
            en_shiftChar: 'C',
        },
        {
            code: 'KeyV',
            en_char: 'v',
            ru_char: 'м',
            ru_shiftChar: 'М',
            en_shiftChar: 'V',
        },
        {
            code: 'KeyB',
            en_char: 'b',
            ru_char: 'и',
            ru_shiftChar: 'И',
            en_shiftChar: 'B',
        },
        {
            code: 'KeyN',
            en_char: 'n',
            ru_char: 'т',
            ru_shiftChar: 'Т',
            en_shiftChar: 'N',
        },
        {
            code: 'KeyM',
            en_char: 'm',
            ru_char: 'ь',
            ru_shiftChar: 'Ь',
            en_shiftChar: 'M',
        },
        {
            code: 'Comma',
            en_char: ',',
            ru_char: 'б',
            ru_shiftChar: 'Б',
            en_shiftChar: '<',
        },
        {
            code: 'Period',
            en_char: '.',
            ru_char: 'ю',
            ru_shiftChar: 'Ю',
            en_shiftChar: '>',
        },
        {
            code: 'Slash',
            en_char: '/',
            ru_char: '.',
            ru_shiftChar: ',',
            en_shiftChar: '?',
        },
        {
            code: 'ArrowUp',
            display: '↑',
        },
        {
            code: 'ShiftRight',
            display: 'Shift ⇧',
        },
      
    ],
    [
        {
            code: 'ControlLeft',
            display: 'Ctrl',
        },
        {
            code: 'MetaLeft',
            display: 'Win',
        },
        {
            code: 'AltLeft',
            display: 'Alt',
        },
        {
            code: 'Space',
            char: ' ',
        },
        {
            code: 'AltRight',
            display: 'Alt',
        },
        {
            code: 'ArrowLeft',
            display: '←',
        },
        {
            code: 'ArrowDown',
            display: '↓',
        },
        {
            code: 'ArrowRight',
            display: '→',
        },
        {
            code: 'ControlRight',
            display: 'Ctrl',
        },
       
    ],
];
